#!/usr/bin/perl
use JSON;
use LWP::Simple;
my $MHOME="/home/cl/mining-scheduler/Mining-Scheduler";
my $GPUS=0;

#
#Pull what we are mining
#

open my $file, '<', "$MHOME/run/miner" || die "Couldn't open $file: $!";
$mining = <$file>;
chomp($mining);
close $file;

#
# Load mining-scheduler miners.cfg to find the miner plugin
#
open my $file, "<", "$MHOME/miners.cfg" || die "Couldn't open $file: $!";
while (<$file>) {
if ( $_ =~ /^$mining/ ) {
	my @val = split(":", $_);
	$pluginname=@val[2];
}
}
$pluginname="phoenixminer";

#
# load the plugins and select the correct one
#
$plugin="$MHOME/node_exporter/plugins/$pluginname.pm";
require $plugin;


my ($pool, $user, $miner, $total_watts, $total_hashrate, $total_shares_accepted, $total_shares_submitted, $gpu_temp, $gpu_fanspeed, $gpu_watts, $gpu_hashrate, $gpu_shares_accepted, $gpu_shares_submitted)=$pluginname->mstats();
  #
  # Output Stats
  #
  #open my $file, ">", "/var/lib/prometheus/node-exporter/miner.prom" || die "Couldn't open $file: $!";
  open my $file, ">", "./test.txt" || die "Couldn't open $file: $!";
  print $file "mining_scheduler{pool=\"$pool\",user=\"$user\",mining=\"$mining\",miner=\"$miner\"} 1\n";
  print $file "mining_scheduler_total_watts{mining=\"$mining\",miner=\"$miner\"} $total_watts\n";
  print $file "mining_scheduler_total_hashrate{mining=\"$mining\",miner=\"$miner\"} $total_hashrate\n";
  print $file "mining_scheduler_total_shares_accepted{mining=\"$mining\",miner=\"$miner\"} $total_shares_accepted\n";
  print $file "mining_scheduler_total_shares_submitted{mining=\"$mining\",miner=\"$miner\"} $total_shares_submitted\n";

  #
  #Pull GPU Data and output
  #
  $GPUS = @$gpu_temp;
  for (my $i = 0; $i <= $GPUS-1; $i++){
          print $file "mining_scheduler_gpu_temp{gpu=\"$i\",mining=\"$mining\",miner=\"$miner\"} @$gpu_temp[$i]\n";
          print $file "mining_scheduler_gpu_fanspeed{gpu=\"$i\",mining=\"$mining\",miner=\"$miner\"} @$gpu_fanspeed[$i]\n";
          print $file "mining_scheduler_gpu_watts{gpu=\"$i\",mining=\"$mining\",miner=\"$miner\"} @$gpu_watts[$i]\n";
          print $file "mining_scheduler_gpu_hashrate{gpu=\"$i\",mining=\"$mining\",miner=\"$miner\"} @$gpu_hashrate[$i]\n";
          print $file "mining_scheduler_gpu_shares_accepted{gpu=\"$i\",mining=\"$mining\",miner=\"$miner\"} @$gpu_shares_accepted[$i]\n";
          print $file "mining_scheduler_gpu_shares_submitted{gpu=\"$i\",mining=\"$mining\",miner=\"$miner\"} @$gpu_shares_submitted[$i]\n";
  }

