{
 "title": "Mining-Scheduler Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "System",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   { "name": "mining", "query": "mining_scheduler" }
  ]
 },
 "panels": [
  {
   "title": "Currently Mining",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "repeat": "mining",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mining_scheduler{instance=\"$System:9100\"}",
     "legendFormat": "{{miner}} Mining {{mining}}"
    }
   ]
  },
  {
   "title": "Mining Hash Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "expr": "mining_scheduler_gpu_hashrate{instance=\"$System:9100\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Hash rate of unit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "expr": "mining_scheduler_total_hashrate{instance=\"$System:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mining_scheduler_gpu_temp{instance=\"$System:9100\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Fan Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mining_scheduler_gpu_fanspeed{instance=\"$System:9100\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Watts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mining_scheduler_gpu_watts{instance=\"$System:9100\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Total Watts of Unit",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mining_scheduler_total_watts{instance=\"$System:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Shares submitted Per GPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "shares" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mining_scheduler_gpu_shares_submitted{instance=\"$System:9100\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Total Shares submitted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "shares" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mining_scheduler_total_shares_submitted{instance=\"$System:9100\"}",
     "legendFormat": "Total Shares"
    }
   ]
  },
  {
   "title": "Shares Accepted per GPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "shares" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mining_scheduler_gpu_shares_accepted{instance=\"$System:9100\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Shares rejected per GPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "shares" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mining_scheduler_gpu_shares_submitted{instance=\"$System:9100\"}-mining_scheduler_gpu_shares_accepted{instance=\"$System:9100\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}